### PR TITLE
Turn on thoth components in moc cluster

### PR DESCRIPTION
**Pull request by harshad16**
Turn on thoth components in moc cluster
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
Changes applied - @harshad16  can you confirm :)

**Comment by harshad16** [comment]
> Changes applied - @harshad16 can you confirm :)

yes , thank you.
All the changes have been applied.

**Pull request merged**
