### PR TITLE
feat: move slack-first to smaug

### PR DESCRIPTION
**Pull request by mimotej**
Moving slack-first from zero to smaug. 
Related: https://github.com/operate-first/apps/pull/954 .

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
see please: https://github.com/operate-first/apps/pull/954#pullrequestreview-742765406

**Review by tumido — CHANGES_REQUESTED** [review]
slack first app resource still points to the zero cluster, see:

https://github.com/operate-first/argocd-apps/blob/946db80e637f6ea8a1ad84f6fb69003b3a76de7d/envs/moc/smaug/operate-first/slack-first.yaml#L8

Also, can you please rename the overlay from zero to smaug as well?

**Review by tumido — CHANGES_REQUESTED** [review]
Please rebase + polite bump :slightly_smiling_face:

**Comment by mimotej** [comment]
Sorry, didn't notice rebased, fixed and ready for merge.

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/unhold
/lgtm
/approve

**Pull request merged**
