### PR TITLE
feat: Add data catalog and dashboard apps

### PR DESCRIPTION
**Pull request by tumido**

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
What do you think of enabling autosync and pruning?

**Comment by tumido** [comment]
We don't do that for any other apps as of now. I don't mind though. @HumairAK is there any reason for it to be turned off?

**Review by HumairAK — APPROVED** [review]

**Comment by HumairAK** [comment]
there's no reason to be off, we should turn it on for all of them, I'm waiting till the restructuring pr's to do that

**Review by anishasthana — APPROVED** [review]

**Comment by HumairAK** [comment]
[related](https://github.com/operate-first/odh/issues/10)

**Pull request merged**
