### PR TITLE
enable moc-nfs-democratic-csi on zero cluster

### PR DESCRIPTION
**Pull request by larsks**
part of operate-first/SRE#280

### CODE REVIEW

**Comment by tumido** [comment]
/hold

wait for https://github.com/operate-first/apps/pull/614

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]

**Comment by HumairAK** [comment]
bah I made the mistake of thinking this: https://github.com/operate-first/apps/pull/614 got merged, that's fine -- it can sit in error state for a bit while it's merged.

**Comment by tumido** [comment]
https://github.com/operate-first/apps/pull/614 is merged now

**Pull request merged**
