### PR TITLE
include thoth components for test cluster

### PR DESCRIPTION
**Pull request by harshad16**
include thoth components for a test cluster
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by HumairAK** [comment]
I see that `test-thoth-amun-api.yaml` and `test-thoth-revsolver.yaml` weren't included -- is that intended?

**Comment by harshad16** [comment]
> I see that `test-thoth-amun-api.yaml` and `test-thoth-revsolver.yaml` weren't included in the kustomization -- is that intended?

yes it was intended.

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by HumairAK** [comment]
due to the size of this, let's have @tumido sign off as well

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
