### PR TITLE
Enable applyoutofsynconly for large apps and Enable autosync for app-of-apps.

### PR DESCRIPTION
**Pull request by HumairAK**
Resolve: https://github.com/operate-first/argocd-apps/issues/137

As described here: https://argoproj.github.io/argo-cd/user-guide/sync-options/#selective-sync

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
Would you like to apply the same change to [curator cluster-resources](https://github.com/operate-first/argocd-apps/blob/main/envs/moc/curator/cluster-management/cluster-resources.yaml) as well?

**Comment by HumairAK** [comment]
Done -- also added it to the app-of-apps

**Comment by tumido** [comment]
@HumairAK I don't think we want autoupdate on app-of-apps - if we turn of autosync on any nested app manually, the app-of-apps will turn it back on, right away, wouldn't it? Isn't that a side effect of this PR?

**Comment by HumairAK** [comment]
@tumido I imagined that's what we wanted. Is it not?

**Comment by tumido** [comment]
Hm.. I thought the nature of this PR was a bit different though... :smile: Maybe it's semantics, but in contrast to the title and issue this PR is not about "just making sync jobs faster" but it also enforces all application resources to be always in sync with git - which is a side effect and changes the flow (removes the manual non-gitopsy handbrake we had and used in emergency when ArgoCD was fighting over resources).

Let's go with it, sure. Can you please adjust the PR title or description that this is also the effect here?

**Comment by tumido** [comment]
/hold

we have 2 applications with manual changes in the zero cluster. We need to change those specs in git before this gets merged. PR pending: https://github.com/operate-first/argocd-apps/pull/140

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
