### PR TITLE
add b4mad app / minecraft

### PR DESCRIPTION
**Pull request by durandom**
cc @goern 

/hold

### CODE REVIEW

**Comment by durandom** [comment]
/unhold

@tumido pls review

corresponding PR https://github.com/operate-first/continuous-deployment/pull/138

**Review by tumido — COMMENTED** [review]
/lgtm :+1: 
/hold for dependency - `AppProject` has to exist first

**Review by tumido — APPROVED** [review]
/unhold app project is available now
/approve

**Comment by tumido** [comment]
let's try again

/unhold

**Comment by tumido** [comment]
sorry for the delay, I had to fix an unrelated issue in the meantime.

Here's your app, all green

https://argocd-server-argocd.apps.moc-infra.massopen.cloud/applications/minecraft

**Pull request merged**
