### PR TITLE
feat: Add Mailing list analysis toolkit

### PR DESCRIPTION
**Pull request by tumido**
Part of: https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/issues/33

### CODE REVIEW

**Comment by tumido** [comment]
ready to be reviewed and merged

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
please merge https://github.com/operate-first/continuous-deployment/pull/106 first
/hold

**Comment by 4n4nd** [comment]
> please merge [operate-first/continuous-deployment#106](https://github.com/operate-first/continuous-deployment/pull/106) first


mrged /unhold

**Comment by HumairAK** [comment]
this is only updating the base, did you mean to add it to an environment? (probably moc?)

**Comment by tumido** [comment]
@HumairAK The base should be pulled in to the overlay. The manifest is rendered properly on:

```
$ kustomize build overlays/moc/data-science | grep "^  name:"
  name: black-flake
  name: mailing-list-analysis-toolkit
```

looks fine to me

**Pull request merged**
