### PR TITLE
deploy aicoe-ci component via argo cd

### PR DESCRIPTION
**Pull request by harshad16**
deploy aicoe-ci component via argo cd
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/thoth-station/thoth-application/issues/800

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
With more clusters coming to be managed in MOC, it make more sense to me to define application resources in base and only reference them in the target overlays. I leave it to your  discretion though. Moving the resource to `base` will make our lives a bit easier, when we will need to split the single `moc` overlay into multiple ones...

**Comment by harshad16** [comment]
> With more clusters coming to be managed in MOC, it make more sense to me to define application resources in base and only reference them in the target overlays. I leave it to your discretion though. Moving the resource to `base` will make our lives a bit easier, when we will need to split the single `moc` overlay into multiple ones...

I have made the changes required, thanks for the suggestion :)

**Review by HumairAK — APPROVED** [review]

**Review by tumido — APPROVED** [review]

**Review by 4n4nd — APPROVED** [review]

**Pull request merged**
